language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  
script: 
  - cp -a test/. src
  - pip install src/.
  - coverage run src/tests.py

after_success:
  - codecov --token=6ead0a14-6ac4-4692-8ccf-04e2cb3067ac
  
notifications:
  email: false
